export const TODO_CREATE = 'TODO_CREATE'
export const TODO_DESTROY = 'TODO_DESTROY'
export const TODO_UPDATE_TEXT = 'TODO_UPDATE_TEXT'
export const TODO_SEARCH = 'TODO_SEARCH'
export const TODO_ADD = 'TODO_ADD'
export const TODO_SELECT = 'TODO_SELECT'
export const TODO_EDIT = 'TODO_EDIT'
